### ISSUE TITLE
 Cannot find module 'lib/context-node'

### ISSUE THREAD

**Issue by suriyaJaay** [azu/codemirror-console#2]
Trying to create inbrowser code editor, that should compile and run codes for Python and R programming, like online code editors such as codechef, ideone, etc. all my attempts are failed due to no utilize anything effectively. recently i have came across this [https://www.npmjs.com/package/codemirror-console](url) and decided to fallows this.

in my console, it has throws some error as follows. as at beginning stage of using node and anuglarjs, i couldn't make it clear.  

**may be am wrong.  could be better to guide me.**

Error: Cannot find module 'lib/context-node'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at s (F:\codemirror-console-master\app.js:1:176)
    at F:\codemirror-console-master\app.js:1:333
    at Object.__dirname.5../lib/context-browser (F:\codemirror-console-master\app.js:8831:20)
    at s (F:\codemirror-console-master\app.js:1:282)
    at F:\codemirror-console-master\app.js:1:333
    at Object.__dirname.2.codemirror (F:\codemirror-console-master\app.js:33:19)
## steps i followed:

installed required dependencies as per mentioned here [https://www.npmjs.com/package/codemirror-console](url)

tried to run from console like this node app.js

helps appreciated. thank you

**Comment by azu** [comment]
codemirror-console is not node app.
It is for browser.

Run demo app in browser by following steps.

````
git clone https://github.com/azu/codemirror-console
cd codemirror-console
npm i
open index.html
```

**Comment by suriyaJaay** [comment]
@azu  thanks for your response and lead. 
after tried for past 2 days am asking this doubt. could you pls tell me

1. how to change modes to some other programming platform?
2. how to configure this app for **"Python and R programming"** (compile and execute as per existing)?

hope you guys would guide me.
looking forward.  

Thank you
