### ISSUE TITLE
Using codemirror-console in React

### ISSUE THREAD

**Issue by Favourz1** [azu/codemirror-console#21]
Please how can i use codemirror-console with [Codemirror](https://www.npmjs.com/package/codemirror) and [react-codemirror2](https://www.npmjs.com/package/react-codemirror2) in React? 

Thanks

**Comment by azu** [comment]
[codemirror-console](https://github.com/azu/codemirror-console/tree/master/packages/codemirror-console) and [codemirror-console-ui](https://github.com/azu/codemirror-console/blob/master/packages/codemirror-console-ui/README.md) just wrap codemirror.

It is hard to integrate existing Codemirror instance.
Instead of It, Just use DOM API.
https://stackblitz.com/edit/react-ts-vsfe3j?file=App.tsx

**Comment by Favourz1** [comment]
Hello, @azu I left the project due to unforeseen circumstances. Although I'm back now.

The problem now is that the **defaultText**  parameter from the **attachToElement** method in **codemirror-console-ui** doesn't update when my app re-renders (a change in the code editor triggers an app re-render) thus causing my console output to be the initial value of my code editor. I tried using the **setUserContext**  method from **codemirror-console-ui**  with my javascript code editor value as its argument but it gives an error.

`x TypeError: Failed to set an indexed property on 'Window': Indexed property setter is not supported.`

PS: I hid the attached code mirror and left only the console (as that is what I need) through styling.

> Possible Solution: Is there a way I can manually update the  **defaultText** parameter when my app re-renders? Or anyway, can I make my console output show the updated value onChange of my javascript code editor? 

I put this code in a useEffect hook, useLayoutEffect hook, and onBeforeChange of my **CodeMirror** component. But none of them worked.
`if (!isConsoleInitialized.current) {
      setUserContext(javascript)
      attachToElement(consoleRef.current, javascript, {
        state: 'closed',
        scrollIntoView: false,
      });
      isConsoleInitialized.current = true;
    }`
